name: Build and Deploy React App
on:
    push:
        branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '19.x'
            - name: npm cache
              uses: actions/cache@v2
              with:
                path: ~/.npm
                key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm install
            - name: Build App
              run: npm run build
            - name: Save artifact
              uses: actions/upload-artifact@v2
              with:
                name: build-artifact
                path: build
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                name: build-artifact
            - run: ls -alt
            - name: Delete existing files
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER_IP }}
                port: ${{ secrets.SERVER_PORT }}
                username: ${{ secrets.SERVER_USER }}
                password: ${{ secrets.SERVER_PASSWORD }}
                script: rm -rf ${{ secrets.SERVER_PATH }}
            - name: Deploy to Server
              uses: wangyucode/sftp-upload-action@v2.0.2
              with:
                host: ${{ secrets.SERVER_IP }}
                port: ${{ secrets.SERVER_PORT }}
                username: ${{ secrets.SERVER_USER }}
                password: ${{ secrets.SERVER_PASSWORD }}
                localDir: ./build
                remoteDir: ${{ secrets.SERVER_PATH }}
