name: Build and Deploy React App
on:
    push:
        branches:
        - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
            - run: echo "Hello, world!"
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: File list
              run: ls -alt
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '14.x'
            - name: NodeJS check
              run: node -v
            
