name: Build and Deploy React App
on:
    push:
        branches:
        - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '19.x'
            - name: NodeJS check
              run: node -v
            - name: Install Dependencies
              run: npm install
            - name: Build App
              run: npm run build
            - name: File list
              run: ls -alt
            