name: test
on: [push]
jobs:
    test:
        runs-on: ubuntu-lastest
        steps: 
            - run: echo "Hello, world!"
            - uses: actions/checkout@v3
              with:
                # Repository name with owner. For example, actions/checkout
                # Default: ${{ github.repository }}
                repository: ''
