name: test
on:
    push:
        branches:
        - main
jobs:
    test:
        runs-on: ubuntu-lastest
        steps: 
            - run: echo "Hello, world!"
            - uses: actions/checkout@v3
              with:
                repository: ''
